{% set python_min = "3.11" %}
{% set version = "4.14.1" %}

package:
  name: libpysal
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/l/libpysal/libpysal-{{ version }}.tar.gz
  sha256: 84a0a832178e57b54f7da35f1c3385c1eaf99016ec8ff819add3b89d36aaff1c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pytest-runner
    - setuptools >=61.0
    - setuptools-scm >=6.2
  run:
    - jinja2
    - python >={{ python_min }}
    - beautifulsoup4 >=4.13.0
    - geopandas >=0.14.0
    - numpy >=1.26.0
    - packaging >=23.2
    - pandas >=2.1.0
    - platformdirs >=3.11.0
    - requests >=2.32.0
    - scipy >=1.12.0
    - shapely >=2.0
    - scikit-learn >=1.4.0

test:
  imports:
    - libpysal
    - libpysal.cg
    - libpysal.cg.ops
    - libpysal.examples
    - libpysal.graph
    - libpysal.io
    - libpysal.io.geotable
    - libpysal.io.iohandlers
    - libpysal.io.tests
    - libpysal.io.util
    - libpysal.weights
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://pysal.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Core components of PySAL A library of spatial analysis functions

extra:
  recipe-maintainers:
    - ocefpaf
    - jGaboardi
    - martinfleis
