{% set python_min = "3.10" %}
{% set version = "4.13.0" %}

package:
  name: libpysal
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/l/libpysal/libpysal-{{ version }}.tar.gz
  sha256: 71a07f7a2e705632862c15c51af5171a42391c874a7efd6711f06c7e4e9c6f53

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pytest-runner
    - setuptools >=61.0
    - setuptools-scm >=6.2
  run:
    - python >={{ python_min }}
    - beautifulsoup4 >=4.10
    - geopandas >=0.10.0
    - numpy >=1.22
    - packaging >=22
    - pandas >=1.4
    - platformdirs >=2.0.2
    - requests >=2.27
    - scipy >=1.8
    - shapely >=2.0.1
    - scikit-learn >=1.1

test:
  imports:
    - libpysal
    - libpysal.cg
    - libpysal.cg.ops
    - libpysal.examples
    - libpysal.graph
    - libpysal.io
    - libpysal.io.geotable
    - libpysal.io.iohandlers
    - libpysal.io.tests
    - libpysal.io.util
    - libpysal.weights
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://pysal.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Core components of PySAL A library of spatial analysis functions

extra:
  recipe-maintainers:
    - ocefpaf
    - jGaboardi
    - martinfleis
