{% set version = "4.9.0" %}

package:
  name: libpysal
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/libpysal/libpysal-{{ version }}.tar.gz
  sha256: 35bd71d3f37089ce0c408e96143052323de22b6a60d9000be1ab28ea0928975e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - pytest-runner
    - setuptools >=61.0
    - setuptools-scm >=6.2
  run:
    - python >=3.8
    - platformdirs
    - beautifulsoup4
    - jinja2
    - numpy >=1.3
    - packaging
    - pandas >=1.4
    - requests
    - scipy >=1.8
    - geopandas
    - shapely >=2.0

test:
  imports:
    - libpysal
    - libpysal.cg
    - libpysal.cg.ops
    - libpysal.examples
    - libpysal.graph
    - libpysal.io
    - libpysal.io.geotable
    - libpysal.io.iohandlers
    - libpysal.io.tests
    - libpysal.io.util
    - libpysal.weights
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pysal.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Core components of PySAL A library of spatial analysis functions

extra:
  recipe-maintainers:
    - ocefpaf
    - jGaboardi
    - martinfleis
